#!/usr/bin/env sh

file="$1"; shift
case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
    *.tar*) tar tf "$file" ;;
    *.zip) unzip -l "$file" ;;
    *.rar) unrar l "$file" ;;
    *.7z) 7z l "$file" ;;
    *)
        batcat -p "$file"
        ;;
esac
