# monitor.alsa.rules = [
#   {
#     matches = [
#       {
#         device.name = "alsa_card.usb-Sony_IER-EX15C_000000-00"
#       }
#     ]
#     actions = {
#       update-props = {
#         priority.session = 20000
#         priority.driver = 20000
#       }
#     }
#   }
# ]
