set -g history-limit 100000
set -g repeat-time 0
set -sg escape-time 50
set -g focus-events on
set -g mouse on
set -g mode-keys vi

set -g prefix C-t
bind C-t send-prefix

#not a fan of rotate window
unbind C-o 

bind l split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind k kill-pane

bind -T copy-mode-vi v send -X begin-selection 
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi Enter send -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi Escape send -X cancel

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Status bar
set -g status-style "bg=#373737,fg=white"

# Left/right sections
set -g status-left-style "bg=#373737,fg=white"
set -g status-right-style "bg=#373737,fg=white"
set -g status-right ""

# Inactive windows
setw -g window-status-style "bg=#373737,fg=#d0d0d0"

# Active/selected window
setw -g window-status-current-style "bg=#4a4a4a,fg=white,bold"

# Optional formatting
setw -g window-status-format " #W "
setw -g window-status-current-format " #W "
