#################################
#       General Settings        #
#################################
# Use GLX for Intel Integrated Graphics
backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovlp-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;
log-level = "warn";
